# Generated by Django 2.1.3 on 2018-11-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181129_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
